name: PORTEFOLIO CI & DEPLOY

on:
  push:
    branches:
      - main # Le déploiement ne se fera que si tu pushes sur la branche principale

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      # 1. Installation des dépendances
      - name: Install dependencies
        run: pnpm install

      # 2. Le test ESLint (si cette étape échoue, le déploiement s'arrête !)
      - name: Lint
        run: pnpm run lint

      # 3. Le build de ton application
      - name: Build
        run: pnpm run build

      # 4. Installation de la Vercel CLI
      - name: Install Vercel CLI
        run: pnpm add -g vercel

      # 5. Le déploiement sur Vercel (seulement si le lint et le build ont réussi)
      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}